blank_issues_enabled: false
contact_links:
  - name: MagentaRV Discord Server
    url: https://discord.me/MagentaRV
    about: Have questions or need support? Please go to the Discord server as issues that are just support-related will be closed and redirected there.
